version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend:/app/build
    depends_on:
      - backend
    networks:
    - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    expose:
      - 8000
    volumes:
      - static:/vol/static
    env_file:
      - .env
    networks:
    - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
    - backend

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/vol/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
    - backend

volumes:
  static:
  frontend:

networks:
  backend: