# Generated by Django 5.0 on 2024-01-08 03:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitoring_alerta_compra_monitoring_alerta_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoring',
            unique_together={('user', 'codigo_acao')},
        ),
    ]
