export const MONITORING_DELETE_REQUEST = 'MONITORING_DELETE_REQUEST';
export const MONITORING_DELETE_SUCCESS = 'MONITORING_DELETE_SUCCESS';
export const MONITORING_DELETE_FAIL = 'MONITORING_DELETE_FAIL';

export const MONITORING_EDIT_REQUEST = 'MONITORING_EDIT_REQUEST';
export const MONITORING_EDIT_SUCCESS = 'MONITORING_EDIT_SUCCESS';
export const MONITORING_EDIT_FAIL = 'MONITORING_EDIT_FAIL';

export const CREATE_MONITORING_REQUEST = 'CREATE_MONITORING_REQUEST';
export const CREATE_MONITORING_SUCCESS = 'CREATE_MONITORING_SUCCESS';
export const CREATE_MONITORING_FAIL = 'CREATE_MONITORING_FAIL';