export const PRICE_MONITOR_LIST_REQUEST = 'PRICE_MONITOR_LIST_REQUEST';
export const PRICE_MONITOR_LIST_SUCCESS = 'PRICE_MONITOR_LIST_SUCCESS';
export const PRICE_MONITOR_LIST_FAIL = 'PRICE_MONITOR_LIST_FAIL';
